version: "3.9"

services:
  web:
    image: pismo-api
    ports:
    - "3000:3000"
    command: "./script/start"
    links:
    - db
    environment:
    - POSTGRESQL_URL=postgres://pismo:pismo@db:5432/pismo_api?sslmode=disable
    - API_PORT=3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.0-alpine3.18
    environment:
    - POSTGRES_DB=pismo_api
    - POSTGRES_USER=pismo
    - POSTGRES_PASSWORD=pismo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pismo -d pismo_api"]
      interval: 10s
      timeout: 5s
      retries: 10